### ISSUE TITLE
Auth help

### ISSUE THREAD

**Issue by imilne** [Pyhass/Pyhiveapi#40]
I'm trying to use this API in standalone mode on the command line (rather than via something like Home Assistant) and the following code was working fine up until a few days ago, when it suddenly started failing with *An error occurred (NotAuthorizedException) when calling the InitiateAuth operation: Invalid Refresh Token*
```
from pyhiveapi import Hive, SMS_REQUIRED

session = Hive(username="", password="")
login = session.login()

if login.get("ChallengeName") == SMS_REQUIRED:
    code = input("Enter 2FA code: ")
    session.sms_2fa(code, login)

session.startSession()

HeatingDevices = session.deviceList["climate"]

if len(HeatingDevices) >= 1:
    HeatingZone_1 = HeatingDevices[0]
    print("temperature=" + str(session.heating.getCurrentTemperature(HeatingZone_1)))
    print("targetTemperature=" + str(session.heating.getTargetTemperature(HeatingZone_1)))
    print("state=" + str(session.heating.getCurrentOperation(HeatingZone_1)))
```
Is there something else I need to be doing here? The Hive integration via Home Assistant is still ok (as is the Hive app on my phone), so I assume they haven't changed the API again.

**Comment by sddunne** [comment]
Hi, i'm also having this issue as of a couple of days ago!

**Comment by sdunnedeloitte** [comment]
@imilne - did you have any luck figuring out the issue, i'm stumped!

**Comment by imilne** [comment]
Not so far, no. It's probably something simple, but I'm not a Python programmer and can barely understand the stack trace as it is. The examples (https://github.com/Pyhass/pyhiveapi.docs/tree/main/docs/examples) show a few different options but even there I'm not sure if there's anything that'll help as I think it's out of date.

**Comment by sdunnedeloitte** [comment]
Best I can come up with is that it looks like Hive are hosting on AWS and using Cognito and something looks like it’s maybe changed either on the backend or in the boto authentication somehow.

Noticed the dev branch had some minor changes made a couple of months ago and tried installing the library from that branch but no effect sadly!

From: Iain Milne ***@***.***>
Date: Thursday, 21 April 2022 at 16:22
To: Pyhass/Pyhiveapi ***@***.***>
Cc: Dunne, Sean ***@***.***>, Manual ***@***.***>
Subject: [EXT] Re: [Pyhass/Pyhiveapi] Auth help (Issue #40)

Not so far, no. It's probably something simple, but I'm not a Python programmer and can barely understand the stack trace as it is. The examples (https://github.com/Pyhass/pyhiveapi.docs/tree/main/docs/examples<https://secure-web.cisco.com/1Kw9Z6nFn2Za3r1WvRfOqfalXQEqVUFQ83JNZy31y5rUgSSU5yg3sfI7cQcT0KmQ28jup2WQ-U1RnixABCbNKT6WmAugJXd3ovehjhEUR5krWkm-wfLGM7h9F0jsQHt3VRz5wJbkkjqgYM1z1gFxAM5aH697aK7omq200bNzlEO3qiPQR0ukHSSn8O64TYxPQUY-VOtRtqfMuVYmNDVFOUEtDnn7xIt7LIECrBkCi73Nt-NWp82DlWqrurTAT_hwFambWUveDNJt3bnwJnuGqHHo2oZLDXZt09fzbZzBZtTrrk1bo6VC2UUvvT36ltGJi/https%3A%2F%2Fgithub.com%2FPyhass%2Fpyhiveapi.docs%2Ftree%2Fmain%2Fdocs%2Fexamples>) show a few different options but even there I'm not sure if there's anything that'll help as I think it's out of date.

—
Reply to this email directly, view it on GitHub<https://secure-web.cisco.com/1B6N-Hi4g3-rjRAEoFerQkr_kzQ2W4T8lF3t5cZ1xyv-SNAAqmP4JWFTqrk6MYPTPpSslBHDKIArKMEqOXTVOGkQUFLtI9my0frVoVhBWepvk6kKaCWrFPg9dHoWi2rd-aJIncBgCTLFWTKOqRTeKNSE90ZJ5rWpfXNgv2diaCP6xOAj4NJ5myxXJWtNot195tLqM4GlNwNIujTIqiqXgrAMU-YdMZScgv_PMvK4-DlR-fKOS-y6L1dbd0PMli7dD636wql9w4LP4iubXCSLTHxHNQ21RgGOfazqWAs7G3eOQuwK2a6iH2zsyaeICvXh2/https%3A%2F%2Fgithub.com%2FPyhass%2FPyhiveapi%2Fissues%2F40%23issuecomment-1105372289>, or unsubscribe<https://secure-web.cisco.com/1iA58AzCieXHqkjE6-_5gM7cqYHIq5UTvX3nhOuEUl8xiFz7-VeV3L1S97J3x9OSejjVygKwGZoM2x7wZvfVVaERRfJDyPzCzC4zINm86NTdtELOlc9RMgIYU0iPuDz-2c3mpgOokERu4L_u4PnGdTjJN_nF7x6a6tSwqiKP9asJs6dJ-Y6fLpYpS9VB3dlkS_OXmfGy-KVAbUIWaw446Puy1jSgFPhYWrPgT8LvKU2fZWYndU47FiG84tzEAg5QIPOOP8JmkiLMc25H-CSipH1543esVJFPDZ1NPwJCTDyG_zN-DlDivS0GR-XmZzVmx/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMNHZPOUCMOIUGS2LWEM6ATVGFXBDANCNFSM5TP7DAHA>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
IMPORTANT NOTICE

This communication is from Deloitte LLP, a limited liability partnership registered in England and Wales with registered number OC303675. Its registered office is 1 New Street Square, London EC4A 3HQ, United Kingdom. Deloitte LLP is the United Kingdom affiliate of Deloitte NSE LLP, a member firm of Deloitte Touche Tohmatsu Limited, a UK private company limited by guarantee (“DTTL”). DTTL and each of its member firms are legally separate and independent entities. DTTL and Deloitte NSE LLP do not provide services to clients. Please see www.deloitte.co.uk/about<https://www.deloitte.co.uk/about> to learn more about our global network of member firms. For details of our professional regulation please see Regulators<https://www2.deloitte.com/uk/en/footerlinks1/regulators-and-provision-service-regulations.html>.

This communication contains information which is confidential and may also be privileged. It is for the exclusive use of the intended recipient(s). If you are not the intended recipient(s), please notify ***@***.******@***.***> and destroy this message immediately. Email communications cannot be guaranteed to be secure or free from error or viruses. All emails sent to or from a @deloitte.co.uk email account are securely archived and stored by an external supplier within the European Union.

You can understand more about how we collect and use (process) your personal information in our Privacy Notice<https://www2.deloitte.com/uk/en/legal/privacy.html>.

Deloitte LLP does not accept any liability for use of or reliance on the contents of this email by any person save by the intended recipient(s) to the extent agreed in a Deloitte LLP engagement contract.

Opinions, conclusions and other information in this email which have not been delivered by way of the business of Deloitte LLP are neither given nor endorsed by it.

**Comment by Dopeyr** [comment]
My _hunch_ on this is that Hive has enabled device tracking / remembered devices in AWS Cognito. 

There is a new(?) option in the Hive app under "Account Security" called "Trusted Devices". When I login with a browser at https://my.hivehome.com, my browser appears here in the app.

See https://aws.amazon.com/blogs/mobile/tracking-and-remembering-devices-using-amazon-cognito-your-user-pools/

The bit that stands out from the above link is:

>The access token only works for one hour, but a new one can be retrieved with the refresh token, as long as the refresh token is valid. **With device tracking, these tokens are linked to a single device. If a refresh token is used on any other device, the call fails.**

My hunch is as the refresh token API call is not specifying a device_key (AFAIK) it's treated as a new device, and as refresh tokens are linked to devices, the API call fails.

The Hive integration works for 1 hour until the token expires, the refresh token API is called but fails, and integration stops working.

I don't know how to confirm if this is correct, but a separate integration I have (PHP-based, unrelated to HA / this library) started failing too at the refresh API call.

**Comment by atph** [comment]
I am currently using this in a small script, and I too ran into the 
`raise HiveInvalid2FACode`, (I was running version 0.4.3 found using `pip show pyhiveapi` )

After an upgrade using `pip install pyhiveapi --upgrade`  I moved up to version 0.5.1. Where the error changed to
`botocore.errorfactory.NotAuthorizedException: An error occurred (NotAuthorizedException) when calling the InitiateAuth operation: Invalid Refresh Token.`

My current workaround was to comment the line asking to refresh the tokens (line 348 in sesssions.py)
` elif self.tokens is not None:
348                 #self.hiveRefreshTokens()
349                 api_resp_d = self.api.getAll()`

**Comment by imilne** [comment]
@atph - that seems to be working for me too, so well done and thanks for figuring that out! I'm also running via cron btw.

**Comment by KJonline** [comment]
Hi all,

0.5.3 was release a week again which implements the new Amazon Cognito remembered devices functionality. Also refresh token was updated to accommodate this as well. Updated documentation has been published on the pyhiveapi doc site which can be found here https://pyhass.github.io/pyhiveapi.docs/docs/examples/api/

**Comment by sdunnedeloitte** [comment]
Excellent, thank you!

From: Khole ***@***.***>
Date: Wednesday, 18 May 2022 at 20:50
To: Pyhass/Pyhiveapi ***@***.***>
Cc: Dunne, Sean ***@***.***>, Manual ***@***.***>
Subject: [EXT] Re: [Pyhass/Pyhiveapi] Auth help (Issue #40)

Hi all,

0.5.3 was release a week again which implements the new Amazon Cognito remembered devices functionality. Also refresh token was updated to accommodate this as well. Updated documentation has been published on the pyhiveapi doc site which can be found here https://pyhass.github.io/pyhiveapi.docs/docs/examples/api/<https://secure-web.cisco.com/1-eDMMT1l_Jy1eViVciqvbOLwV7tfDObERG1iV6EEKZmRiHyjVYrlriRWcaUrI_iI9YKjuB3XS9wX5Ar2aboTbEyJjmbm1uN7YnwnBeJrypHiTumdGqvvhElEPXsyZVXaio55eAQCwS8ibC-oLYubkPtcHsxFwWITgcV5IImCu4n-s7H4xxe3tmhcrePCbFGQkONnV8A_cyXTXSokGoMwfIlJVRfpBZFB_AkwVUl1UjwNZyDSRySfeI-E-7gaWzIjyhGPXNnFcWuLLv1OVkffwtYasF3Qs4zqhbIXEwHTNa5mDgzWvjEeWxA0gudV9O6I/https%3A%2F%2Fpyhass.github.io%2Fpyhiveapi.docs%2Fdocs%2Fexamples%2Fapi%2F>

—
Reply to this email directly, view it on GitHub<https://secure-web.cisco.com/1hPjZRoYov7bZcO76T6gT57qkMwOmXksKAJODFNNvgP2D0T84Ey61xzYn3Zjtsz4R_430rBQiN_T5Lm-CCsITIDalP3YxiaDz3hFB5-RU18EX86f6aM2HjvAJy_Uz_iI9RgoQ62Z-gxC3EHOxefF3mMqX5nCnpYOpA3vLyVC_M2mwmbKsvAdu5wp0srlscxlLBPjsAEbbseEZLSpjp33dvCXhGJFYBNUhepbLnkAx822lMw5sunR9n4b1R9GMJfHag4M0JUkUEE8e0HA_vfL_aOQunUbhvD_QREWsuKqFlXJZghGsRvPFHrihs-q3R9x_nFE4CUSa_Z7rf3Omq2sqYA/https%3A%2F%2Fgithub.com%2FPyhass%2FPyhiveapi%2Fissues%2F40%23issuecomment-1130470896>, or unsubscribe<https://secure-web.cisco.com/19TkzOeVaNqxX7jlM51xc5fa8GypmMGQ-hZXTjGHoYJwrFrQL724sFrrjcx8XsW6YFEGZKUaot8cyTuHWifK2pCYWsDpD-5Ng165rGZ2KjKKTQPNt17oRX1zm_BPupJ4dfgc_cChM6HyOShLv6gQJ4uynIPwN1gFaaCyQqKivLxA4m7p0Oh_q4snKMaDOm_pehKJ2FUR1YhLrJzFEG5q_vSHnEi6dekz74KxSasUlphXccQopza4APCQ7Z7gzXsX3CGPk_diW1-eRY37BvYRIDeCKbX3-64ScVbIdwo3dpcogx9QjibuwKDsSnJRgy_eHcdY5pAQ56bHLBqDDvw8Akg/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMNHZPKGJQFJA2DGNQEWRB3VKVCVBANCNFSM5TP7DAHA>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
IMPORTANT NOTICE

This communication is from Deloitte LLP, a limited liability partnership registered in England and Wales with registered number OC303675. Its registered office is 1 New Street Square, London EC4A 3HQ, United Kingdom. Deloitte LLP is the United Kingdom affiliate of Deloitte NSE LLP, a member firm of Deloitte Touche Tohmatsu Limited, a UK private company limited by guarantee (“DTTL”). DTTL and each of its member firms are legally separate and independent entities. DTTL and Deloitte NSE LLP do not provide services to clients. Please see www.deloitte.co.uk/about<https://www.deloitte.co.uk/about> to learn more about our global network of member firms. For details of our professional regulation please see Regulators<https://www2.deloitte.com/uk/en/footerlinks1/regulators-and-provision-service-regulations.html>.

This communication contains information which is confidential and may also be privileged. It is for the exclusive use of the intended recipient(s). If you are not the intended recipient(s), please notify ***@***.******@***.***> and destroy this message immediately. Email communications cannot be guaranteed to be secure or free from error or viruses. All emails sent to or from a @deloitte.co.uk email account are securely archived and stored by an external supplier within the European Union.

You can understand more about how we collect and use (process) your personal information in our Privacy Notice<https://www2.deloitte.com/uk/en/legal/privacy.html>.

Deloitte LLP does not accept any liability for use of or reliance on the contents of this email by any person save by the intended recipient(s) to the extent agreed in a Deloitte LLP engagement contract.

Opinions, conclusions and other information in this email which have not been delivered by way of the business of Deloitte LLP are neither given nor endorsed by it.
